### ISSUE TITLE
Any chance you could choose a license type for this?

### ISSUE THREAD

**Issue by Ezekiel-Kruglick** [RobRomijnders/LSTM_tsc#13]
Any chance you could choose a license type for this?

I might recommend MIT license as most likely to lead to more people using it 👍

**Comment by RobRomijnders** [comment]
What is the advantage of using a license? Everything I put on github is open to everyone

**Comment by Ezekiel-Kruglick** [comment]
Actually, without a written license applied to the project the default copyright of the law applies. That is very restrictive.

See the "Your project doesn't have a license" section here: 
https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/

Easy way to pick a license:
https://choosealicense.com/

**Comment by RobRomijnders** [comment]
Good to learn about this. Thank you for informing me.

I have included the MIT license. 

I will add licenses to my other github repo's during the Christmas clean up

**Comment by Ezekiel-Kruglick** [comment]
Thank YOU, kind sir. And happy holidays!
