### ISSUE TITLE
TypeError 'The value of a feed cannot be a tf.Tensor object. '

### ISSUE THREAD

**Issue by ghost** [RobRomijnders/LSTM_tsc#2]
raise type error with tensorflow 0.11rc0; numpy 1.11.1; python 2.7.12; macOS 10.12;

Train with approximately 60 epochs
tsc_main.py:23: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  X_batch = X_train[ind_N,ind_start:ind_start+num_steps]
At     0 out of  2000: Cost is TRAIN1.734(1.390) VAL1.599 and val acc is 0.400
At   100 out of  2000: Cost is TRAIN1.380(1.387) VAL1.376 and val acc is 0.300
At   200 out of  2000: Cost is TRAIN1.288(1.339) VAL1.159 and val acc is 0.733
At   300 out of  2000: Cost is TRAIN1.010(1.171) VAL1.106 and val acc is 0.567
At   400 out of  2000: Cost is TRAIN0.935(1.044) VAL1.041 and val acc is 0.533
At   500 out of  2000: Cost is TRAIN1.058(0.982) VAL0.776 and val acc is 0.633
At   600 out of  2000: Cost is TRAIN0.774(0.908) VAL1.153 and val acc is 0.633
At   700 out of  2000: Cost is TRAIN0.823(0.866) VAL0.643 and val acc is 0.833
At   800 out of  2000: Cost is TRAIN0.626(0.814) VAL0.876 and val acc is 0.633
At   900 out of  2000: Cost is TRAIN1.140(0.793) VAL0.792 and val acc is 0.600
At  1000 out of  2000: Cost is TRAIN0.800(0.753) VAL0.835 and val acc is 0.733
At  1100 out of  2000: Cost is TRAIN0.890(0.746) VAL0.571 and val acc is 0.767
At  1200 out of  2000: Cost is TRAIN0.634(0.725) VAL1.061 and val acc is 0.400
At  1300 out of  2000: Cost is TRAIN0.851(0.715) VAL0.550 and val acc is 0.767
At  1400 out of  2000: Cost is TRAIN0.504(0.694) VAL0.682 and val acc is 0.600
At  1500 out of  2000: Cost is TRAIN0.647(0.706) VAL0.870 and val acc is 0.567
At  1600 out of  2000: Cost is TRAIN0.490(0.702) VAL0.430 and val acc is 0.800
At  1700 out of  2000: Cost is TRAIN0.585(0.695) VAL0.548 and val acc is 0.767
At  1800 out of  2000: Cost is TRAIN1.013(0.676) VAL0.638 and val acc is 0.800
At  1900 out of  2000: Cost is TRAIN0.937(0.649) VAL0.817 and val acc is 0.600
tsc_main.py:31: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  test_acc = np.zeros(num_batch)
Traceback (most recent call last):
  File "tsc_main.py", line 178, in <module>
    acc_test = check_test(X_test,y_test,batch_size,num_steps)
  File "tsc_main.py", line 34, in check_test
    test_acc[i] = sess.run(accuracy,feed_dict = {input_data: X_batch, targets: y_batch, initial_state:state,keep_prob:1})
  File "/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 875, in _run
    raise TypeError('The value of a feed cannot be a tf.Tensor object. '
TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, or numpy ndarrays.

**Comment by pribadihcr** [comment]
@zhenpingfeng 
same error. is there already solution ?

**Comment by RobRomijnders** [comment]
I'll look into it

**Comment by RobRomijnders** [comment]
I made a correction. Does it work now?

**Comment by pribadihcr** [comment]
Hi @RobRomijnders,

Yes, it worked. Thanks
